openapi: "3.0.3"
info:
  title: "trade_crossing_ktor API"
  description: "trade_crossing_ktor API"
  version: "1.0.0"
servers:
- url: "https://trade_crossing_ktor"
paths:
  /oauth/google/callback:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/OAuthResponse"
  /oauth/google/login:
    get:
      description: ""
  /oauth/kakao/callback:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/OAuthResponse"
  /oauth/kakao/login:
    get:
      description: ""
components:
  schemas:
    OAuthResponse:
      type: "object"
      properties:
        registered:
          type: "boolean"
        profilePic:
          type: "string"
        accessToken:
          type: "string"
        refreshToken:
          type: "string"
      required:
      - "profilePic"
      - "accessToken"
      - "refreshToken"