name: 'Deploy to Light Sail'
on:
  push:
    branches:
      - dev
  workflow_dispatch:
env:
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}
  AWS_REGION: 'ap-northeast-2'
  SSH_KEY: ${{secrets.SSH_KEY}}
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: 권한 부여
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Make Directory
        run: mkdir -p deploy

      - name: Copy jar file
        run: cp build/libs/*.jar deploy/

      - name: Deploy using ssh
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu/app
          SOURCE: build/libs/tradecrossing.jar
          SCRIPT_BEFORE: |
            whoami
            ls -al
